# Generated by Django 4.2.7 on 2023-11-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.TextField()),
                ('set', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.idioma')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.images')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.moneda')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.type')),
            ],
        ),
    ]
