# Generated by Django 4.2.7 on 2023-12-05 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.TextField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.moneda')),
            ],
        ),
    ]
