# Generated by Django 4.2.7 on 2023-12-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='carid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
